/**
 * ASTROCAL — Celestial Events Master Dataset
 * Accurate astronomical data, coordinates, peak times, and viewing parameters
 */

const CELESTIAL_EVENTS = [
  {
    id: 'perseids-2026',
    title: 'Perseid Meteor Shower Peak',
    category: 'meteor-shower',
    categoryLabel: 'Meteor Shower',
    icon: '☄️',
    date: '2026-08-30',
    displayDate: 'August 30, 2026',
    time: '21:00 Local / 15:30 UTC',
    peakWindow: '9:00 PM – 4:30 AM',
    daysAway: 6,
    rate: '100–120 meteors/hr',
    radiant: 'Perseus (RA: 03h 04m, Dec: +58°)',
    altitude: '48° NE',
    moonPhase: 'Waning Crescent (12% Illumination - Excellent)',
    visibilityScore: 96,
    bortleOptimal: 'Class 1–4 (Dark Sky to Rural)',
    equipment: 'Naked Eye (No telescope required)',
    featured: true,
    locationHighlights: [
      { name: 'Pune, India', visible: true, bestTime: '9:30 PM – 4:00 AM', direction: 'Northeast', altitude: '42°' },
      { name: 'Tokyo, Japan', visible: true, bestTime: '10:00 PM – 4:30 AM', direction: 'Northeast', altitude: '55°' },
      { name: 'New York, USA', visible: true, bestTime: '10:30 PM – 5:00 AM', direction: 'Northeast', altitude: '62°' },
      { name: 'London, UK', visible: true, bestTime: '10:00 PM – 4:30 AM', direction: 'Northeast', altitude: '68°' },
      { name: 'Atacama, Chile', visible: true, bestTime: '1:00 AM – 5:00 AM', direction: 'Northern Horizon', altitude: '22°' }
    ],
    description: 'The Perseids are renowned as one of the most prolific and brightest annual meteor showers. Produced by Comet Swift-Tuttle, they frequently leave long glowing wakes and vibrant green/blue fireballs tearing across the upper atmosphere at 59 km/s.',
    viewingTips: 'Lie back on a reclining chair facing Northeast. Allow 25 minutes for your eyes to adapt to total darkness. Avoid white flashlight screens; use red light only.',
    badgeColor: '#00DFD8',
    gradient: 'linear-gradient(135deg, rgba(0, 223, 216, 0.2), rgba(121, 40, 202, 0.3))'
  },
  {
    id: 'solar-eclipse-2026',
    title: 'Great Total Solar Eclipse',
    category: 'eclipse',
    categoryLabel: 'Solar Eclipse',
    icon: '🌑',
    date: '2026-09-12',
    displayDate: 'September 12, 2026',
    time: '17:45 UTC',
    peakWindow: '4m 28s Totality',
    daysAway: 19,
    rate: '100% Sun Coverage (Totality)',
    radiant: 'Constellation Leo',
    altitude: '58° SW',
    moonPhase: 'New Moon (0% Illumination)',
    visibilityScore: 99,
    bortleOptimal: 'Any (Daytime Event)',
    equipment: 'ISO 12312-2 Solar Eclipse Glasses / Solar Filter',
    featured: true,
    locationHighlights: [
      { name: 'Northern Spain & Iceland', visible: true, bestTime: '5:35 PM – 5:45 PM Local', direction: 'Southwest', altitude: '32°' },
      { name: 'London, UK', visible: true, bestTime: 'Partial 92% (5:20 PM)', direction: 'West-Southwest', altitude: '28°' },
      { name: 'Pune, India', visible: false, bestTime: 'Nighttime (Live Stream Available)', direction: 'Below Horizon', altitude: '-45°' },
      { name: 'New York, USA', visible: false, bestTime: 'Partial 35% at Sunrise', direction: 'Eastern Horizon', altitude: '12°' }
    ],
    description: 'The Moon completely obscures the solar disk, revealing the ethereal dancing ribbons of the Sun’s white outer corona and pink solar prominences. The temperature noticeably drops and stars become visible in the afternoon sky.',
    viewingTips: 'Never look directly at the uneclipsed or partially eclipsed sun without certified ISO 12312-2 solar filters. Remove filters only during the brief 100% totality window.',
    badgeColor: '#F59E0B',
    gradient: 'linear-gradient(135deg, rgba(245, 158, 11, 0.25), rgba(220, 38, 38, 0.3))'
  },
  {
    id: 'planetary-alignment-2026',
    title: 'Grand 5-Planet Alignment Parade',
    category: 'planetary',
    categoryLabel: 'Planetary Alignment',
    icon: '🪐',
    date: '2026-09-24',
    displayDate: 'September 24, 2026',
    time: '04:30 Local (Pre-Dawn)',
    peakWindow: '4:15 AM – 5:40 AM',
    daysAway: 31,
    rate: '5 Planets in Arc (Mercury, Venus, Mars, Jupiter, Saturn)',
    radiant: 'Ecliptic Arc East to South',
    altitude: '15° to 65° along Ecliptic',
    moonPhase: 'Waxing Crescent (8% Illumination)',
    visibilityScore: 92,
    bortleOptimal: 'Class 1–6 (Suburban / Dark Sky)',
    equipment: 'Naked Eye for All 5; Binoculars/Telescope for Saturn Rings & Jupiter Moons',
    featured: true,
    locationHighlights: [
      { name: 'Pune, India', visible: true, bestTime: '4:40 AM – 5:35 AM', direction: 'East to South', altitude: '52°' },
      { name: 'Tokyo, Japan', visible: true, bestTime: '4:15 AM – 5:10 AM', direction: 'East-Southeast', altitude: '45°' },
      { name: 'London, UK', visible: true, bestTime: '5:00 AM – 6:00 AM', direction: 'East-Southeast', altitude: '38°' },
      { name: 'New York, USA', visible: true, bestTime: '4:50 AM – 5:45 AM', direction: 'East-Southeast', altitude: '44°' },
      { name: 'Sydney, Australia', visible: true, bestTime: '5:05 AM – 5:55 AM', direction: 'East to North', altitude: '58°' }
    ],
    description: 'A rare celestial configuration where Mercury, Venus, Mars, Jupiter, and Saturn string across the morning sky in their exact orbital order from the Sun. A stunning geometric sight across the zodiac.',
    viewingTips: 'Find an unobstructed eastern horizon. Venus and Jupiter will shine with dazzling brilliance, while Mercury will hover just above the dawn twilight.',
    badgeColor: '#8B5CF6',
    gradient: 'linear-gradient(135deg, rgba(139, 92, 246, 0.25), rgba(6, 182, 212, 0.3))'
  },
  {
    id: 'super-harvest-moon-2026',
    title: 'Super Harvest Blood Moon Eclipse',
    category: 'supermoon',
    categoryLabel: 'Supermoon / Lunar Eclipse',
    icon: '🌕',
    date: '2026-10-06',
    displayDate: 'October 6, 2026',
    time: '20:15 Local / 14:45 UTC',
    peakWindow: '8:15 PM – 11:30 PM',
    daysAway: 43,
    rate: 'Perigee at 357,100 km (14% Larger, 30% Brighter)',
    radiant: 'Constellation Pisces',
    altitude: '65° SE',
    moonPhase: 'Full Supermoon (100% Illumination)',
    visibilityScore: 98,
    bortleOptimal: 'Any (Visible from Urban centers)',
    equipment: 'Naked eye / Binoculars / Small telescope',
    featured: false,
    locationHighlights: [
      { name: 'Pune, India', visible: true, bestTime: '8:00 PM – Midnight', direction: 'East to Overhead', altitude: '72°' },
      { name: 'Tokyo, Japan', visible: true, bestTime: '7:30 PM – 1:00 AM', direction: 'South-East', altitude: '65°' },
      { name: 'London, UK', visible: true, bestTime: '8:30 PM – 2:00 AM', direction: 'South-East', altitude: '54°' },
      { name: 'New York, USA', visible: true, bestTime: '7:45 PM – 1:30 AM', direction: 'East-Southeast', altitude: '60°' }
    ],
    description: 'The closest full moon of the autumn season coincides with a deep penumbral lunar eclipse. As the Earth casts its shadow, the lunar disk glows with coppery crimson tones as Rayleigh scattering filters sunset light through Earth’s atmosphere.',
    viewingTips: 'Watch during moonrise when the "Moon Illusion" makes it appear giant against trees and city skylines on the horizon.',
    badgeColor: '#EC4899',
    gradient: 'linear-gradient(135deg, rgba(236, 72, 153, 0.25), rgba(249, 115, 22, 0.3))'
  },
  {
    id: 'orionids-2026',
    title: 'Orionid Meteor Shower (Halley’s Comet Trail)',
    category: 'meteor-shower',
    categoryLabel: 'Meteor Shower',
    icon: '✨',
    date: '2026-10-21',
    displayDate: 'October 21, 2026',
    time: '01:00 Local / 19:30 UTC',
    peakWindow: 'Midnight – 5:00 AM',
    daysAway: 58,
    rate: '25–35 meteors/hr (Hyper-fast 66 km/s)',
    radiant: 'Orion the Hunter (RA: 06h 20m, Dec: +16°)',
    altitude: '55° SE',
    moonPhase: 'Waxing Gibbous (Setting at 1:30 AM)',
    visibilityScore: 88,
    bortleOptimal: 'Class 1–3 (Dark Rural Sky)',
    equipment: 'Naked Eye',
    featured: false,
    locationHighlights: [
      { name: 'Pune, India', visible: true, bestTime: '1:30 AM – 5:00 AM', direction: 'East to Overhead', altitude: '68°' },
      { name: 'Tokyo, Japan', visible: true, bestTime: '2:00 AM – 5:00 AM', direction: 'South-East', altitude: '58°' },
      { name: 'London, UK', visible: true, bestTime: '1:00 AM – 5:00 AM', direction: 'South', altitude: '50°' },
      { name: 'New York, USA', visible: true, bestTime: '1:30 AM – 5:00 AM', direction: 'South-Southeast', altitude: '56°' }
    ],
    description: 'Debris left behind by the legendary Halley’s Comet (1P/Halley) collides with Earth. Orionids are exceptionally fast and known for leaving persistent glowing ionization trains lasting up to several seconds.',
    viewingTips: 'Best viewed after 1:30 AM once the moon has set. Locate the bright stars of Orion’s Belt, but gaze 30° away from the radiant point to catch the longest meteor trails.',
    badgeColor: '#10B981',
    gradient: 'linear-gradient(135deg, rgba(16, 185, 129, 0.25), rgba(6, 182, 212, 0.3))'
  },
  {
    id: 'geminids-2026',
    title: 'Geminid King of Meteor Showers',
    category: 'meteor-shower',
    categoryLabel: 'Meteor Shower',
    icon: '🌠',
    date: '2026-12-14',
    displayDate: 'December 14, 2026',
    time: '22:00 Local / 16:30 UTC',
    peakWindow: '9:00 PM – 5:30 AM',
    daysAway: 112,
    rate: '150 meteors/hr (Dense, Multi-Colored)',
    radiant: 'Gemini (near Castor & Pollux)',
    altitude: '78° Overhead',
    moonPhase: 'Waxing Crescent (Sets early evening - 0% moonlight)',
    visibilityScore: 99,
    bortleOptimal: 'Class 1–5 (Rural / Suburb)',
    equipment: 'Naked Eye / Reclining Chair / Warm Blanket',
    featured: true,
    locationHighlights: [
      { name: 'Pune, India', visible: true, bestTime: '10:00 PM – 4:30 AM', direction: 'Overhead Zenith', altitude: '82°' },
      { name: 'Tokyo, Japan', visible: true, bestTime: '9:30 PM – 4:30 AM', direction: 'Overhead', altitude: '78°' },
      { name: 'London, UK', visible: true, bestTime: '9:00 PM – 5:00 AM', direction: 'Overhead South', altitude: '70°' },
      { name: 'New York, USA', visible: true, bestTime: '9:30 PM – 4:30 AM', direction: 'Overhead South', altitude: '74°' }
    ],
    description: 'The undisputed monarch of meteor showers. Unlike most showers originating from comets, the Geminids originate from asteroid 3200 Phaethon. Meteors are slow, bright, and often exhibit vibrant emerald green, golden yellow, and blue colors.',
    viewingTips: 'Dress warmly with thermal layers. The show begins as early as 9 PM and intensifies toward 2 AM when the Gemini radiant climbs directly overhead.',
    badgeColor: '#6366F1',
    gradient: 'linear-gradient(135deg, rgba(99, 102, 241, 0.25), rgba(236, 72, 153, 0.3))'
  },
  {
    id: 'iss-pass-pune',
    title: 'International Space Station (ISS) Bright Pass',
    category: 'satellite',
    categoryLabel: 'Spacecraft Transit',
    icon: '🛰️',
    date: '2026-08-28',
    displayDate: 'August 28, 2026',
    time: '19:42 Local',
    peakWindow: '6 minutes transit (19:42 – 19:48)',
    daysAway: 4,
    rate: 'Magnitude -3.9 (Brighter than Venus)',
    radiant: 'SW to NE Horizon Transit',
    altitude: 'Max Elevation: 79° Overhead',
    moonPhase: 'Waning Crescent',
    visibilityScore: 97,
    bortleOptimal: 'Any (Easily visible even in city centers)',
    equipment: 'Naked Eye (No equipment needed)',
    featured: false,
    locationHighlights: [
      { name: 'Pune, India', visible: true, bestTime: '7:42 PM – 7:48 PM', direction: 'SW to NE (Passes Zenith)', altitude: '79°' },
      { name: 'Mumbai, India', visible: true, bestTime: '7:41 PM – 7:47 PM', direction: 'SW to NE', altitude: '75°' },
      { name: 'Bangalore, India', visible: true, bestTime: '7:43 PM – 7:49 PM', direction: 'West to NE', altitude: '62°' }
    ],
    description: 'The orbital laboratory carrying 7 astronauts will streak silently across the night sky, reflecting brilliant sunlight off its football-field-sized solar arrays. One of the brightest artificial objects in orbit.',
    viewingTips: 'Look towards the Southwest horizon at exactly 7:42 PM. It will look like a steady, fast-moving bright white star moving smoothly without blinking.',
    badgeColor: '#00DFD8',
    gradient: 'linear-gradient(135deg, rgba(0, 223, 216, 0.2), rgba(59, 130, 246, 0.3))'
  }
];

const OBSERVATION_LOCATIONS = [
  { id: 'pune', name: 'Pune, India', lat: 18.5204, lon: 73.8567, bortle: 5, elevation: '560m', timezone: 'IST (UTC+5:30)' },
  { id: 'tokyo', name: 'Tokyo, Japan', lat: 35.6762, lon: 139.6503, bortle: 8, elevation: '40m', timezone: 'JST (UTC+9:00)' },
  { id: 'london', name: 'London, UK', lat: 51.5074, lon: -0.1278, bortle: 7, elevation: '35m', timezone: 'BST (UTC+1:00)' },
  { id: 'newyork', name: 'New York, USA', lat: 40.7128, lon: -74.0060, bortle: 8, elevation: '10m', timezone: 'EDT (UTC-4:00)' },
  { id: 'atacama', name: 'Atacama Desert, Chile', lat: -23.8634, lon: -69.1328, bortle: 1, elevation: '2400m', timezone: 'CLT (UTC-3:00)' },
  { id: 'maunakea', name: 'Mauna Kea Observatory, Hawaii', lat: 19.8206, lon: -155.4681, bortle: 1, elevation: '4205m', timezone: 'HST (UTC-10:00)' },
  { id: 'sydney', name: 'Sydney, Australia', lat: -33.8688, lon: 151.2093, bortle: 6, elevation: '20m', timezone: 'AEST (UTC+10:00)' }
];

window.CELESTIAL_EVENTS = CELESTIAL_EVENTS;
window.OBSERVATION_LOCATIONS = OBSERVATION_LOCATIONS;
